baseURL = "https://for.ai/"
languageCode = "en-us"
title = "FOR.ai"

[params.team]
  [params.team.Aidan]
    title = 'Aidan Gomez'
    bio = 'Aidan is a machine learning researcher with the University of Toronto Machine Learning Group. Works on core machine learning theory; trying to give theoretical explanations to empirically observed phenomena.'
    date = '2017-10-17'
    img = 'img/aidan.jpg'
    link='https://aidangomez.ca'
    order = 1
    email_suffix = 'aidan'
  [params.team.Ivan]
    title = 'Ivan Zhang'
    date = '2017-10-17'
    img = 'img/ivan.png'
    link = 'https://ivanzhang.ca'
    order = 2
    email_suffix = 'ivan'
  [params.team.Bryan]
    title = 'Bryan Li'
    bio = ''
    date = '2017-10-17'
    img = 'img/bryan.jpg'
    link = 'https://bryanli.io'
    order = 3
    email_suffix = 'bryan'
  [params.team.Sheldon]
    title = 'Sheldon Huang'
    bio = ''
    date = '2017-10-17'
    img = 'img/sheldon.png'
    link='https://www.cs.toronto.edu/~huang/'
    order = 4
    email_suffix = 'sheldon'
  [params.team.Divyam]
    title = 'Divyam Madaan'
    bio = ''
    date = '2017-10-17'
    img = 'img/divyam.jpg'
    link='https://www.linkedin.com/in/dmadaan3897/'
    order = 5
    email_suffix = 'divyam'
  [params.team.Siddhartha]
    title = 'Siddhartha Rao Kamalakara'
    bio = ''
    date = '2017-10-17'
    img = 'img/siddhartha.jpg'
    link='https://www.linkedin.com/in/siddhartha-rao-kamalakara/'
    order = 6
    email_suffix = 'siddhartha'
  [params.team.Nitarshan]
    title = "Nitarshan Rajkumar"
    bio = ""
    date = "2019-01-10"
    img = "img/nitarshan.jpg"
    link = "https://www.nitarshan.com/"
    order = 9
    email_suffix = 'nitarshan'
  [params.team.Alex]
    title = "Alexander Cowen-Rivers"
    bio = ""
    date = "2019-03-19"
    img = "img/alex.jpg"
    link = "https://alexanderimanicowenrivers.github.io/"
    order = 10
    email_suffix = 'alex'
  [params.team.Hari]
    title = "Hariharan Sezhiyan"
    bio = ""
    date = "2019-07-09"
    img = "img/hari.png"
    link = "https://hsezhiyan.github.io/Thoughts/"
    order = 11
    email_suffix = 'hari'
  [params.team.Piotr]
    title = "Piotr Kozakowski"
    bio = ""
    date = "2019-07-11"
    img = "img/piotr.png"
    link = "https://github.com/koz4k"
    order = 12
    email_suffix = 'piotr'
  [params.team.Winnie]
    title = "Winnie Xu"
    bio = ""
    date = "2019-10-24"
    img = "img/winnie.png"
    link = "https://winniexu.ca"
    order = 13
    email_suffix = 'winnie'
  [params.team.Acyr]
    title = "Acyr Locatelli"
    bio = ""
    date = "2019-10-24"
    img = "img/acyr.jpg"
    link = "https://acyrl.github.io/"
    order = 14
    email_suffix = 'acyr'
  [params.team.Alessandro]
    title = "Alessandro Melis"
    bio = ""
    date = "2019-10-24"
    img = "img/alessandro.jpg"
    link = "https://alemelis.gitlab.io/"
    order = 15
    email_suffix = 'alessandro'
  [params.team.Mert]
    title = "Mert Yüksekgönül"
    bio = ""
    date = "2019-10-24"
    img = "img/mert.jpg"
    link = "https://www.linkedin.com/in/mertyuksekgonul/"
    order = 16
    email_suffix = 'mert'
  [params.team.Amr]
    title = "Amr Kayid"
    bio = ""
    date = "2020-10-21"
    img = "img/amr.jpg"
    link = "https://amrmkayid.github.io/"
    order = 17
    email_suffix = 'amr'
