baseURL = "https://for.ai/"
languageCode = "en-us"
title = "FOR.ai"

[params.team]
  [params.team.Aidan]
    title = 'Aidan Gomez'
    bio = 'Aidan is a machine learning researcher with the University of Toronto Machine Learning Group. Works on core machine learning theory; trying to give theoretical explanations to empirically observed phenomena.'
    date = '2017-10-17'
    img = 'img/aidan.jpg'
    link='https://aidangomez.ca'
    order = 1
    email_suffix = 'aidan'
  [params.team.Ivan]
    title = 'Ivan Zhang'
    date = '2017-10-17'
    img = 'img/ivan.png'
    link = 'https://ivanzhang.ca'
    order = 2
    email_suffix = 'ivan'
  [params.team.Bryan]
    title = 'Bryan Li'
    bio = ''
    date = '2017-10-17'
    img = 'img/bryan.jpg'
    link = 'https://bryanli.io'
    order = 3
    email_suffix = 'bryan'
  [params.team.Sheldon]
    title = 'Sheldon Huang'
    bio = ''
    date = '2017-10-17'
    img = 'img/sheldon.png'
    link='https://www.cs.toronto.edu/~huang/'
    order = 4
    email_suffix = 'sheldon'
  [params.team.Divyam]
    title = 'Divyam Madaan'
    bio = ''
    date = '2017-10-17'
    img = 'img/divyam.jpg'
    link='https://www.linkedin.com/in/dmadaan3897/'
    order = 5
    email_suffix = 'divyam'
  [params.team.Siddhartha]
    title = 'Siddhartha Rao Kamalakara'
    bio = ''
    date = '2017-10-17'
    img = 'img/siddhartha.jpg'
    link='https://www.linkedin.com/in/siddhartha-rao-kamalakara/'
    order = 6
    email_suffix = 'siddhartha'
  [params.team.Nitarshan]
    title = "Nitarshan Rajkumar"
    bio = ""
    date = "2019-01-10"
    img = "img/nitarshan.jpg"
    link = "https://www.nitarshan.com/"
    order = 9
    email_suffix = 'nitarshan'
  [params.team.Alex]
    title = "Alexander Cowen-Rivers"
    bio = ""
    date = "2019-03-19"
    img = "img/alex.jpg"
    link = "https://alexanderimanicowenrivers.github.io/"
    order = 10
    email_suffix = 'alex'
  [params.team.Hari]
    title = "Hariharan Sezhiyan"
    bio = ""
    date = "2019-07-09"
    img = "img/hari.png"
    link = "https://hsezhiyan.github.io/Thoughts/"
    order = 11
    email_suffix = 'hari'
